name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Determine new version
        id: version
        run: echo ::set-output name=version::$(jq -r '.version' package.json)

      - name: Build package
        run: npm run build
